[workspace]
members = [
   "./analyzer-dispatcher",
   "./derive-dynamic-node",
   "./endpoint-plugin",
   "./generators/generic-subgraph-generator",
   "./generators/graph-generator-lib",
   "./generators/osquery-subgraph-generator",
   "./generators/sysmon-subgraph-generator",
   "./graph-descriptions",
   "./graph-merger",
   "./graph-mutation-service",
   "./grapl",
   "./grapl-config",
   "./grapl-model-plugin-deployer",
   "./grapl-observe",
   "./grapl-service",
   "./grapl-utils",
   "./metric-forwarder",
   "./node-identifier",
   "./sqs-executor",
   "./sysmon",
   "./test-rust-grpc",
]
