---
env:
  PANTS_CONFIG_FILES: "['pants.toml', 'pants.ci.toml']"

# This is defined in a separate pipeline file because
# chronotc/monorepo-diff does not currently have support for plugin
# configuration on commands.

steps:
  - label: ":yarn: Build UX Assets"
    command: "make ux-tarball"
    plugins:
      - docker#v3.8.0:
          image: "node:16.5.0"
    artifact_paths:
      - dist/grapl-ux.tar.gz

  - wait

  - label: ":cloudsmith: Upload UX Assets"
    command:
      - ".buildkite/scripts/upload_ux_assets.sh"
    plugins:
      - seek-oss/aws-sm#v2.3.1:
          env:
            CLOUDSMITH_API_KEY: "cloudsmith-token"
    agents:
      queue: "artifact-uploaders"
