[package]
name = "grapl-graph-descriptions"
version = "0.2.10"
authors = ["Insanitybit <insanitybit@gmail.com>"]
edition = "2018"
description = "A library for interacting with Grapl graphs"
license = "MIT"

[dependencies]
log = "0.4"
prost = "0.7"
prost-derive = "0.7"
prost-types = "0.7"
rand = "0.8"
serde = "1"
serde_derive = "1"
tracing = "0.1.22"
arbitrary = { version="1" }
tonic = { version="0.4" }

[dependencies.uuid]
version = "0.8"
features = ["v4"]

[build-dependencies]
prost-build = "0.7"

tonic-build = { version="0.4", features = ["prost"] }

[dev-dependencies]
test-env-log = "0.2"
quickcheck = "1.0"
quickcheck_macros = { version="1" }
tracing-subscriber = "0.2"

[features]
default = []


[package.metadata.cargo-udeps.ignore]
build=["uuid"]
